### ISSUE TITLE
Migrating the grpc library

### ISSUE THREAD

**Issue by hayarobi** [aergoio/herajs#148]
Currently herajs depends on [grpc](https://www.npmjs.com/package/grpc) package, which was deprecated and recommeneded using [@grpc/grpc-js](https://www.npmjs.com/package/@grpc/grpc-js) instead.

Since this deprecated grpc package supports up to nodejs 14, I had some troubles about the dependencies tree. Is it hard to to release a new version of herajs with migrating just this dependency only? Or is there any way to manipulate the dependency setting in package.json to use @grpc/grpc-js instead of this?

**Comment by findmytrueself** [comment]
#162
