### ISSUE TITLE
Not clear how to send batch transactions

### ISSUE THREAD

**Issue by aspiers** [aergoio/herajs#94]
herapy has [nice support for batch transactions](https://github.com/aergoio/herapy/blob/ce4cb80a84ac61740bf9e521b5fab73639f40ab7/examples/smartcontract_batch_call.py#L85-L94).

However there is no obvious equivalent in the documentation for herajs.  If batch transactions are not possible in herajs yet, please consider this as a feature request.  Otherwise it's just a documentation bug ;-)

**Comment by graup** [comment]
What exactly are batch transactions? Just a method to send multiple txs at once to the blockchain? I can easily add that.

**Comment by aspiers** [comment]
[**@graup**](https://github.com/graup) commented on [March 19, 2020 2:55 AM](https://github.com/aergoio/herajs/issues/94#issuecomment-600960836 "2020-03-19T02:55:27Z - Replied by Github Reply Comments"):
> What exactly are batch transactions? Just a method to send multiple txs at once to the blockchain? I can easily add that.

Yes, please see the linked example in herapy.  Thanks that would be great!

**Comment by graup** [comment]
Fixed in f2dc66ec4079e75f82bf2c74973f38a6cd515ad1, published on npm as 0.19.0.

**Comment by aspiers** [comment]
Excellent, thanks a lot!
